apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  # - ingress.yaml  # Uncomment if using ingress

commonLabels:
  app: todo-app
  managed-by: argocd

namespace: default